print('Hello Tiltfile')
local_resource('unittest',cmd='go test -v', deps=['*.go', 'scripts/*.go'])
k8s_yaml('stock.yml')
secret_text = local('python ./secret_file.py')
k8s_yaml(secret_text)
docker_build('vorsprung/stock','.')
k8s_resource('stockapp', port_forwards='9000')